# Generated by Django 3.0.2 on 2020-02-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('date', models.DateField()),
                ('open_time', models.TimeField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('place', models.CharField(max_length=1024, null=True)),
                ('detail', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', '進行中'), ('finished', '終了')], default='active', max_length=8)),
            ],
        ),
    ]
