# Generated by Django 3.0.2 on 2020-02-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200208_2334'),
        ('concerts', '0002_auto_20200209_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='events',
            field=models.ManyToManyField(blank=True, to='events.Event'),
        ),
    ]
