# Generated by Django 3.0.2 on 2020-02-06 01:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventuser',
            unique_together={('event', 'user')},
        ),
    ]
