# Generated by Django 3.0.2 on 2020-02-08 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200206_1054'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventanswer',
            unique_together={('event', 'value')},
        ),
    ]
