# Generated by Django 3.0.2 on 2020-01-27 03:33

from django.core.management import call_command
from django.db import migrations

def load_fixture(apps, schema_editor):
    call_command('loaddata', 'member/fixture/init.json', app_label='app')

class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20200126_1957'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
