# Generated by Django 3.0.2 on 2020-01-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20200127_1525'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Part',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.DeleteModel(
            name='UserStatus',
        ),
        migrations.AlterField(
            model_name='user',
            name='part',
            field=models.CharField(choices=[('vn1', '1st Violin'), ('vn2', '2nd Violin'), ('va', 'Viola'), ('vc', 'Cello'), ('cb', 'Contrabass'), ('fl', 'Flute'), ('cl', 'Clarinet'), ('sax', 'Saxophone'), ('ob', 'Oboe'), ('fg', 'Fagotto'), ('tp', 'Trumpet'), ('tb', 'Trombone'), ('tu', 'Tuba'), ('gt', 'Guitar'), ('pf', 'Piano'), ('syn', 'Synchesizer'), ('bs', 'Electric Bass'), ('cho-sp', 'Chorus Soprano'), ('cho-al', 'Chorus Alto'), ('cho-tn', 'Chorus Tenor'), ('cho-bs', 'Chorus Bass'), ('cond', 'Conductor'), ('staff', 'Staff')], default='staff', max_length=6),
        ),
    ]
