# Generated by Django 3.0.2 on 2020-01-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=100)),
                ('home_address', models.CharField(max_length=256)),
                ('work_address', models.CharField(max_length=256)),
                ('emergency_phone', models.CharField(max_length=15)),
            ],
        ),
    ]
